### ISSUE TITLE
Does the input file have to be a Seurat object?

### ISSUE THREAD

**Issue by xmliu01** [Papatheodorou-Group/scGOclust#3]
Hi, I am using the package scGOclust to analyze my scRNA-seq data. 
I have done a comparison of different cell types within the species, and I find that using scGOclust to compare the GO BP profiles of cell types is better than comparing only the cell type expression profiles. 
I would also like to compare the cell type across species. 
However, the published article is not an analysis done with Seurat, I can only get their count matrix. 
How do I use scGOclust if I only have count matrix and cell clustering information?

**Comment by YY-SONG0718** [comment]
Hello! Sure it is possible. You can create a Seurat object using the count matrix and the cell metadata. 

`obj <- CreateSeuratObject(counts=counts, assay = "RNA", meta.data = meta.data)`

Seurat object here is just a carrier for scGOclust to conduct the computations.

**Comment by xmliu01** [comment]
> Hello! Sure it is possible. You can create a Seurat object using the count matrix and the cell metadata.
> 
> `obj <- CreateSeuratObject(counts=counts, assay = "RNA", meta.data = meta.data)`
> 
> Seurat object here is just a carrier for scGOclust to conduct the computations.

Thanks, It worked for me.
