### ISSUE TITLE
scGOclust to compare with Drosophila to help identify cell types

### ISSUE THREAD

**Issue by Jiahe-Sun** [Papatheodorou-Group/scGOclust#4]
Hello,

I would like to inquire that the tissue and organ of my research species (Bombyx silk gland) is specific to Bombyx mori. In this case, can I use scGOclust to compare with Drosophila to help identify cell types?

**Comment by YY-SONG0718** [comment]
hello,

Does Bombyx mori have GO annotation? A quick search appeared that some literature has performed GO analysis so I believe a gene-to-GO mapping table is available.

In this case, you are welcome to use scGOclust!
